# Generated by Django 5.2 on 2025-04-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='language',
            field=models.CharField(default='uz', max_length=20, verbose_name='Til'),
        ),
    ]
