# Generated by Django 5.2 on 2025-04-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_botuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
