# Generated by Django 5.2 on 2025-04-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_botuser_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi (ru)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(default="Tavsif yo'q", verbose_name='Tavsifi (uz)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nomi (ru)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(default='Mahsulot nomi', max_length=200, verbose_name='Nomi (uz)'),
            preserve_default=False,
        ),
    ]
