# Generated by Django 5.2 on 2025-04-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_product_description_remove_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='fio',
            new_name='full_name',
        ),
    ]
