# Generated by Django 5.2 on 2025-05-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='Yetkazib berish manzili'),
        ),
    ]
